# Generated by Django 5.1.2 on 2024-10-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zraszacze_api', '0002_device_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sensor_number', models.IntegerField()),
                ('read_value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zraszacze_api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sensor_number', models.IntegerField()),
                ('read_value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zraszacze_api.device')),
            ],
        ),
    ]
